// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: self.proto

package com.example.selfmessage;

public final class SelfDescribingMessage2 {
  private SelfDescribingMessage2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SelfDescribingMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:selfmessage.SelfDescribingMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
     */
    boolean hasProtoFiles();
    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSet getProtoFiles();
    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getProtoFilesOrBuilder();

    /**
     * <pre>
     * Name of the message type.  Must be defined by one of the files in
     * proto_files.
     * </pre>
     *
     * <code>required string type_name = 2;</code>
     */
    boolean hasTypeName();
    /**
     * <pre>
     * Name of the message type.  Must be defined by one of the files in
     * proto_files.
     * </pre>
     *
     * <code>required string type_name = 2;</code>
     */
    java.lang.String getTypeName();
    /**
     * <pre>
     * Name of the message type.  Must be defined by one of the files in
     * proto_files.
     * </pre>
     *
     * <code>required string type_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeNameBytes();

    /**
     * <pre>
     * The message data.
     * </pre>
     *
     * <code>required bytes message_data = 3;</code>
     */
    boolean hasMessageData();
    /**
     * <pre>
     * The message data.
     * </pre>
     *
     * <code>required bytes message_data = 3;</code>
     */
    com.google.protobuf.ByteString getMessageData();
  }
  /**
   * Protobuf type {@code selfmessage.SelfDescribingMessage}
   */
  public  static final class SelfDescribingMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:selfmessage.SelfDescribingMessage)
      SelfDescribingMessageOrBuilder {
    // Use SelfDescribingMessage.newBuilder() to construct.
    private SelfDescribingMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SelfDescribingMessage() {
      typeName_ = "";
      messageData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SelfDescribingMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = protoFiles_.toBuilder();
              }
              protoFiles_ = input.readMessage(com.google.protobuf.DescriptorProtos.FileDescriptorSet.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(protoFiles_);
                protoFiles_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              typeName_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              messageData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.selfmessage.SelfDescribingMessage2.internal_static_selfmessage_SelfDescribingMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.selfmessage.SelfDescribingMessage2.internal_static_selfmessage_SelfDescribingMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage.class, com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage.Builder.class);
    }

    private int bitField0_;
    public static final int PROTO_FILES_FIELD_NUMBER = 1;
    private com.google.protobuf.DescriptorProtos.FileDescriptorSet protoFiles_;
    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
     */
    public boolean hasProtoFiles() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
     */
    public com.google.protobuf.DescriptorProtos.FileDescriptorSet getProtoFiles() {
      return protoFiles_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : protoFiles_;
    }
    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
     */
    public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getProtoFilesOrBuilder() {
      return protoFiles_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : protoFiles_;
    }

    public static final int TYPE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object typeName_;
    /**
     * <pre>
     * Name of the message type.  Must be defined by one of the files in
     * proto_files.
     * </pre>
     *
     * <code>required string type_name = 2;</code>
     */
    public boolean hasTypeName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Name of the message type.  Must be defined by one of the files in
     * proto_files.
     * </pre>
     *
     * <code>required string type_name = 2;</code>
     */
    public java.lang.String getTypeName() {
      java.lang.Object ref = typeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          typeName_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Name of the message type.  Must be defined by one of the files in
     * proto_files.
     * </pre>
     *
     * <code>required string type_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeNameBytes() {
      java.lang.Object ref = typeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString messageData_;
    /**
     * <pre>
     * The message data.
     * </pre>
     *
     * <code>required bytes message_data = 3;</code>
     */
    public boolean hasMessageData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * The message data.
     * </pre>
     *
     * <code>required bytes message_data = 3;</code>
     */
    public com.google.protobuf.ByteString getMessageData() {
      return messageData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProtoFiles()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTypeName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getProtoFiles().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getProtoFiles());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, typeName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, messageData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getProtoFiles());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, typeName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, messageData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage)) {
        return super.equals(obj);
      }
      com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage other = (com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage) obj;

      boolean result = true;
      result = result && (hasProtoFiles() == other.hasProtoFiles());
      if (hasProtoFiles()) {
        result = result && getProtoFiles()
            .equals(other.getProtoFiles());
      }
      result = result && (hasTypeName() == other.hasTypeName());
      if (hasTypeName()) {
        result = result && getTypeName()
            .equals(other.getTypeName());
      }
      result = result && (hasMessageData() == other.hasMessageData());
      if (hasMessageData()) {
        result = result && getMessageData()
            .equals(other.getMessageData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasProtoFiles()) {
        hash = (37 * hash) + PROTO_FILES_FIELD_NUMBER;
        hash = (53 * hash) + getProtoFiles().hashCode();
      }
      if (hasTypeName()) {
        hash = (37 * hash) + TYPE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getTypeName().hashCode();
      }
      if (hasMessageData()) {
        hash = (37 * hash) + MESSAGE_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getMessageData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code selfmessage.SelfDescribingMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:selfmessage.SelfDescribingMessage)
        com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.selfmessage.SelfDescribingMessage2.internal_static_selfmessage_SelfDescribingMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.selfmessage.SelfDescribingMessage2.internal_static_selfmessage_SelfDescribingMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage.class, com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage.Builder.class);
      }

      // Construct using com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProtoFilesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (protoFilesBuilder_ == null) {
          protoFiles_ = null;
        } else {
          protoFilesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        typeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        messageData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.selfmessage.SelfDescribingMessage2.internal_static_selfmessage_SelfDescribingMessage_descriptor;
      }

      public com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage getDefaultInstanceForType() {
        return com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage.getDefaultInstance();
      }

      public com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage build() {
        com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage buildPartial() {
        com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage result = new com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (protoFilesBuilder_ == null) {
          result.protoFiles_ = protoFiles_;
        } else {
          result.protoFiles_ = protoFilesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.typeName_ = typeName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.messageData_ = messageData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage) {
          return mergeFrom((com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage other) {
        if (other == com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage.getDefaultInstance()) return this;
        if (other.hasProtoFiles()) {
          mergeProtoFiles(other.getProtoFiles());
        }
        if (other.hasTypeName()) {
          bitField0_ |= 0x00000002;
          typeName_ = other.typeName_;
          onChanged();
        }
        if (other.hasMessageData()) {
          setMessageData(other.getMessageData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasProtoFiles()) {
          return false;
        }
        if (!hasTypeName()) {
          return false;
        }
        if (!hasMessageData()) {
          return false;
        }
        if (!getProtoFiles().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.DescriptorProtos.FileDescriptorSet protoFiles_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> protoFilesBuilder_;
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
       */
      public boolean hasProtoFiles() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet getProtoFiles() {
        if (protoFilesBuilder_ == null) {
          return protoFiles_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : protoFiles_;
        } else {
          return protoFilesBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
       */
      public Builder setProtoFiles(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (protoFilesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          protoFiles_ = value;
          onChanged();
        } else {
          protoFilesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
       */
      public Builder setProtoFiles(
          com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder builderForValue) {
        if (protoFilesBuilder_ == null) {
          protoFiles_ = builderForValue.build();
          onChanged();
        } else {
          protoFilesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
       */
      public Builder mergeProtoFiles(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (protoFilesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              protoFiles_ != null &&
              protoFiles_ != com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance()) {
            protoFiles_ =
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.newBuilder(protoFiles_).mergeFrom(value).buildPartial();
          } else {
            protoFiles_ = value;
          }
          onChanged();
        } else {
          protoFilesBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
       */
      public Builder clearProtoFiles() {
        if (protoFilesBuilder_ == null) {
          protoFiles_ = null;
          onChanged();
        } else {
          protoFilesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder getProtoFilesBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getProtoFilesFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getProtoFilesOrBuilder() {
        if (protoFilesBuilder_ != null) {
          return protoFilesBuilder_.getMessageOrBuilder();
        } else {
          return protoFiles_ == null ?
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : protoFiles_;
        }
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet proto_files = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> 
          getProtoFilesFieldBuilder() {
        if (protoFilesBuilder_ == null) {
          protoFilesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder>(
                  getProtoFiles(),
                  getParentForChildren(),
                  isClean());
          protoFiles_ = null;
        }
        return protoFilesBuilder_;
      }

      private java.lang.Object typeName_ = "";
      /**
       * <pre>
       * Name of the message type.  Must be defined by one of the files in
       * proto_files.
       * </pre>
       *
       * <code>required string type_name = 2;</code>
       */
      public boolean hasTypeName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * Name of the message type.  Must be defined by one of the files in
       * proto_files.
       * </pre>
       *
       * <code>required string type_name = 2;</code>
       */
      public java.lang.String getTypeName() {
        java.lang.Object ref = typeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            typeName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Name of the message type.  Must be defined by one of the files in
       * proto_files.
       * </pre>
       *
       * <code>required string type_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeNameBytes() {
        java.lang.Object ref = typeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          typeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Name of the message type.  Must be defined by one of the files in
       * proto_files.
       * </pre>
       *
       * <code>required string type_name = 2;</code>
       */
      public Builder setTypeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        typeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name of the message type.  Must be defined by one of the files in
       * proto_files.
       * </pre>
       *
       * <code>required string type_name = 2;</code>
       */
      public Builder clearTypeName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        typeName_ = getDefaultInstance().getTypeName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name of the message type.  Must be defined by one of the files in
       * proto_files.
       * </pre>
       *
       * <code>required string type_name = 2;</code>
       */
      public Builder setTypeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        typeName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString messageData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The message data.
       * </pre>
       *
       * <code>required bytes message_data = 3;</code>
       */
      public boolean hasMessageData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * The message data.
       * </pre>
       *
       * <code>required bytes message_data = 3;</code>
       */
      public com.google.protobuf.ByteString getMessageData() {
        return messageData_;
      }
      /**
       * <pre>
       * The message data.
       * </pre>
       *
       * <code>required bytes message_data = 3;</code>
       */
      public Builder setMessageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        messageData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message data.
       * </pre>
       *
       * <code>required bytes message_data = 3;</code>
       */
      public Builder clearMessageData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messageData_ = getDefaultInstance().getMessageData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:selfmessage.SelfDescribingMessage)
    }

    // @@protoc_insertion_point(class_scope:selfmessage.SelfDescribingMessage)
    private static final com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage();
    }

    public static com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SelfDescribingMessage>
        PARSER = new com.google.protobuf.AbstractParser<SelfDescribingMessage>() {
      public SelfDescribingMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SelfDescribingMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SelfDescribingMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SelfDescribingMessage> getParserForType() {
      return PARSER;
    }

    public com.example.selfmessage.SelfDescribingMessage2.SelfDescribingMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_selfmessage_SelfDescribingMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_selfmessage_SelfDescribingMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nself.proto\022\013selfmessage\032 google/protob" +
      "uf/descriptor.proto\"y\n\025SelfDescribingMes" +
      "sage\0227\n\013proto_files\030\001 \002(\0132\".google.proto" +
      "buf.FileDescriptorSet\022\021\n\ttype_name\030\002 \002(\t" +
      "\022\024\n\014message_data\030\003 \002(\014B1\n\027com.example.se" +
      "lfmessageB\026SelfDescribingMessage2"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_selfmessage_SelfDescribingMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_selfmessage_SelfDescribingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_selfmessage_SelfDescribingMessage_descriptor,
        new java.lang.String[] { "ProtoFiles", "TypeName", "MessageData", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
