// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: selfmessage.proto

package com.example.selfmessage;

public final class SelfDescribingMessageHolder {
  private SelfDescribingMessageHolder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SelfDescribingMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:selfmessage.SelfDescribingMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     */
    boolean hasDescriptorSet();
    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorSet();
    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorSetOrBuilder();

    /**
     * <pre>
     * The message data.
     * </pre>
     *
     * <code>required bytes message_data = 2;</code>
     */
    boolean hasMessageData();
    /**
     * <pre>
     * The message data.
     * </pre>
     *
     * <code>required bytes message_data = 2;</code>
     */
    com.google.protobuf.ByteString getMessageData();
  }
  /**
   * Protobuf type {@code selfmessage.SelfDescribingMessage}
   */
  public  static final class SelfDescribingMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:selfmessage.SelfDescribingMessage)
      SelfDescribingMessageOrBuilder {
    // Use SelfDescribingMessage.newBuilder() to construct.
    private SelfDescribingMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SelfDescribingMessage() {
      messageData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SelfDescribingMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = descriptorSet_.toBuilder();
              }
              descriptorSet_ = input.readMessage(com.google.protobuf.DescriptorProtos.FileDescriptorSet.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(descriptorSet_);
                descriptorSet_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              messageData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SelfDescribingMessageHolder.internal_static_selfmessage_SelfDescribingMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SelfDescribingMessageHolder.internal_static_selfmessage_SelfDescribingMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SelfDescribingMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int DESCRIPTOR_SET_FIELD_NUMBER = 1;
    private com.google.protobuf.DescriptorProtos.FileDescriptorSet descriptorSet_;
    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     */
    public boolean hasDescriptorSet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     */
    public com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorSet() {
      return descriptorSet_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorSet_;
    }
    /**
     * <pre>
     * Set of .proto files which define the type.
     * </pre>
     *
     * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     */
    public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorSetOrBuilder() {
      return descriptorSet_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorSet_;
    }

    public static final int MESSAGE_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString messageData_;
    /**
     * <pre>
     * The message data.
     * </pre>
     *
     * <code>required bytes message_data = 2;</code>
     */
    public boolean hasMessageData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * The message data.
     * </pre>
     *
     * <code>required bytes message_data = 2;</code>
     */
    public com.google.protobuf.ByteString getMessageData() {
      return messageData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDescriptorSet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getDescriptorSet().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getDescriptorSet());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, messageData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDescriptorSet());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, messageData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SelfDescribingMessage)) {
        return super.equals(obj);
      }
      SelfDescribingMessage other = (SelfDescribingMessage) obj;

      boolean result = true;
      result = result && (hasDescriptorSet() == other.hasDescriptorSet());
      if (hasDescriptorSet()) {
        result = result && getDescriptorSet()
            .equals(other.getDescriptorSet());
      }
      result = result && (hasMessageData() == other.hasMessageData());
      if (hasMessageData()) {
        result = result && getMessageData()
            .equals(other.getMessageData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasDescriptorSet()) {
        hash = (37 * hash) + DESCRIPTOR_SET_FIELD_NUMBER;
        hash = (53 * hash) + getDescriptorSet().hashCode();
      }
      if (hasMessageData()) {
        hash = (37 * hash) + MESSAGE_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getMessageData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SelfDescribingMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SelfDescribingMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SelfDescribingMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SelfDescribingMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SelfDescribingMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SelfDescribingMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SelfDescribingMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SelfDescribingMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SelfDescribingMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SelfDescribingMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SelfDescribingMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code selfmessage.SelfDescribingMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:selfmessage.SelfDescribingMessage)
        SelfDescribingMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SelfDescribingMessageHolder.internal_static_selfmessage_SelfDescribingMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SelfDescribingMessageHolder.internal_static_selfmessage_SelfDescribingMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SelfDescribingMessage.class, Builder.class);
      }

      // Construct using com.example.selfmessage.SelfDescribingMessageHolder.SelfDescribingMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDescriptorSetFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (descriptorSetBuilder_ == null) {
          descriptorSet_ = null;
        } else {
          descriptorSetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        messageData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SelfDescribingMessageHolder.internal_static_selfmessage_SelfDescribingMessage_descriptor;
      }

      public SelfDescribingMessage getDefaultInstanceForType() {
        return SelfDescribingMessage.getDefaultInstance();
      }

      public SelfDescribingMessage build() {
        SelfDescribingMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SelfDescribingMessage buildPartial() {
        SelfDescribingMessage result = new SelfDescribingMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (descriptorSetBuilder_ == null) {
          result.descriptorSet_ = descriptorSet_;
        } else {
          result.descriptorSet_ = descriptorSetBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageData_ = messageData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SelfDescribingMessage) {
          return mergeFrom((SelfDescribingMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SelfDescribingMessage other) {
        if (other == SelfDescribingMessage.getDefaultInstance()) return this;
        if (other.hasDescriptorSet()) {
          mergeDescriptorSet(other.getDescriptorSet());
        }
        if (other.hasMessageData()) {
          setMessageData(other.getMessageData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDescriptorSet()) {
          return false;
        }
        if (!hasMessageData()) {
          return false;
        }
        if (!getDescriptorSet().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SelfDescribingMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SelfDescribingMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.DescriptorProtos.FileDescriptorSet descriptorSet_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> descriptorSetBuilder_;
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public boolean hasDescriptorSet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorSet() {
        if (descriptorSetBuilder_ == null) {
          return descriptorSet_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorSet_;
        } else {
          return descriptorSetBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder setDescriptorSet(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (descriptorSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          descriptorSet_ = value;
          onChanged();
        } else {
          descriptorSetBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder setDescriptorSet(
          com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder builderForValue) {
        if (descriptorSetBuilder_ == null) {
          descriptorSet_ = builderForValue.build();
          onChanged();
        } else {
          descriptorSetBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder mergeDescriptorSet(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (descriptorSetBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              descriptorSet_ != null &&
              descriptorSet_ != com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance()) {
            descriptorSet_ =
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.newBuilder(descriptorSet_).mergeFrom(value).buildPartial();
          } else {
            descriptorSet_ = value;
          }
          onChanged();
        } else {
          descriptorSetBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder clearDescriptorSet() {
        if (descriptorSetBuilder_ == null) {
          descriptorSet_ = null;
          onChanged();
        } else {
          descriptorSetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder getDescriptorSetBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDescriptorSetFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorSetOrBuilder() {
        if (descriptorSetBuilder_ != null) {
          return descriptorSetBuilder_.getMessageOrBuilder();
        } else {
          return descriptorSet_ == null ?
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorSet_;
        }
      }
      /**
       * <pre>
       * Set of .proto files which define the type.
       * </pre>
       *
       * <code>required .google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> 
          getDescriptorSetFieldBuilder() {
        if (descriptorSetBuilder_ == null) {
          descriptorSetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder>(
                  getDescriptorSet(),
                  getParentForChildren(),
                  isClean());
          descriptorSet_ = null;
        }
        return descriptorSetBuilder_;
      }

      private com.google.protobuf.ByteString messageData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The message data.
       * </pre>
       *
       * <code>required bytes message_data = 2;</code>
       */
      public boolean hasMessageData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * The message data.
       * </pre>
       *
       * <code>required bytes message_data = 2;</code>
       */
      public com.google.protobuf.ByteString getMessageData() {
        return messageData_;
      }
      /**
       * <pre>
       * The message data.
       * </pre>
       *
       * <code>required bytes message_data = 2;</code>
       */
      public Builder setMessageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        messageData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message data.
       * </pre>
       *
       * <code>required bytes message_data = 2;</code>
       */
      public Builder clearMessageData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageData_ = getDefaultInstance().getMessageData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:selfmessage.SelfDescribingMessage)
    }

    // @@protoc_insertion_point(class_scope:selfmessage.SelfDescribingMessage)
    private static final SelfDescribingMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SelfDescribingMessage();
    }

    public static SelfDescribingMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<SelfDescribingMessage>
        PARSER = new com.google.protobuf.AbstractParser<SelfDescribingMessage>() {
      public SelfDescribingMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SelfDescribingMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SelfDescribingMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SelfDescribingMessage> getParserForType() {
      return PARSER;
    }

    public SelfDescribingMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_selfmessage_SelfDescribingMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_selfmessage_SelfDescribingMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021selfmessage.proto\022\013selfmessage\032 google" +
      "/protobuf/descriptor.proto\"i\n\025SelfDescri" +
      "bingMessage\022:\n\016descriptor_set\030\001 \002(\0132\".go" +
      "ogle.protobuf.FileDescriptorSet\022\024\n\014messa" +
      "ge_data\030\002 \002(\014B6\n\027com.example.selfmessage" +
      "B\033SelfDescribingMessageHolder"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_selfmessage_SelfDescribingMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_selfmessage_SelfDescribingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_selfmessage_SelfDescribingMessage_descriptor,
        new String[] { "DescriptorSet", "MessageData", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
